services:
  history:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: "Dockerfile"
      target: "history"
    env_file:
      - ".env"
    volumes:
      - "./apps/:/app/"
      - "./database/:/app/database/"
    networks:
      local:

  database:
    build:
      dockerfile: "Dockerfile"
      target: "database"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_ROOT_PASSWORD: "${DB_PASS}"
    expose:
      - 3306
    volumes:
      - "./database/dumps/:/docker-entrypoint-initdb.d:ro"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      local:

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - database
    networks:
      local:

networks:
  local:
